apiVersion: v1
kind: ConfigMap
metadata:
  name: video-frontend-config
  namespace: NAMESPACE
data:
  search-suggestions.json: |
    {
      "placeholder_examples": [
        "delivery truck is blocking the road",
        "pizza place around West 80th Street",
        "vehicle is driving on the sidewalk"
      ]
    }
